### ISSUE TITLE
User Authentication for RTL

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTLFullApplication#2]
**Introduction**
Implement an additional authentication layer in RTL, to ensure that access on the LAN is not open to anyone, once LND is unlocked.

**Approach**
Two options will be provided to the user for authentication, depending on the lnd configuration the user is running.
DEFAULT
If the user is running lnd+bitcoind, then bitcoind.rpcpass from the lnd.conf file will be used for session authentication.
CUSTOM
If the user is running lnd+neutrino, then RTL specific password must be provided in the RTL config file.
Authentication will be implemented at session level.
Each browser session opened with the RTL server needs to be authenticated, separately.
Session time-out period will be 60 minutes.

**Config Dependency**
Create a RTL config file `RTL.conf` with a few parameters, which will be read at the initiation of the Node.JS server. The initialization logic of RTL server will be changed to expect the RTL.conf file to be always present.

**Contents of RTL.conf**
`macroonpath=<complete path of the macroon file>`
`lndconfpath=<complete path of the lnd.conf file>`
`authtype=<DEFAULT or CUSTOM>`
`rtlpass=<password>`

**Comment by rootzoll** [comment]
Where will the RTL config be stored?

The RaspiBlitz stores all configuration on the HDD - so that the SD card can be exchanged with a new version/image for repair or update. The path of the HDD is always "/mnt/hdd". We could place the config into a directory called "RTL" (place also if you need to persist more data in the future).
So the final fixed path for a conf could be "/mnt/hdd/RTL/RTL.conf"

Your server could check if there is a file available at such a path and if not use a config that is in your project directory or something for other use cases beside runnign on RaspiBlitz.

**Comment by rootzoll** [comment]
Do you plan multiple users in the future? If not I would recommend to get rid of the `rtluser=<user>` and just use a password for authentification ... like my fritzbox does for example. Its one thing less to remember and to type in - better UX in my experience.

**Comment by saubyk** [comment]
> Where will the RTL config be stored?
> 
> The RaspiBlitz stores all configuration on the HDD - so that the SD card can be exchanged with a new version/image for repair or update. The path of the HDD is always "/mnt/hdd". We could place the config into a directory called "RTL" (place also if you need to persist more data in the future).
> So the final fixed path for a conf could be "/mnt/hdd/RTL/RTL.conf"
> 
> Your server could check if there is a file available at such a path. That would also be a confirmation, that RTL is running on a RaspiBlitz - so when asking for a password, let the user now you are asking for password B. If no file is available at that path you could use a config that is in your project directory or something for other use cases beside running on a RaspiBlitz.

Agree on this. Config file will be placed in the root RTL folder.

**Comment by saubyk** [comment]
> Do you plan multiple users in the future? If not I would recommend to get rid of the `rtluser=<user>` and just use a password for authentification ... like my fritzbox does for example. Its one thing less to remember and to type in - better UX in my experience.

We can just keep the password, not envisioning multiple user roles for RTL.

**Comment by ketominer** [comment]
For the (not so) far future, it would be cool if multiple users could be defined, for example in a small sqlite database, with a different lnd configuration for each user. This way one instance of the RTL installation could be used for multiple lnds. Also, the macaroon could be optionally provided as a hex string and not a path (we are running multiple lnds on multiple servers and RTL would typically run on a separate server / cluster of servers as a front-end to the lnds farm). Also different permission levels (read-only, read-write ...) would be appreciated.

**Comment by ketominer** [comment]
To go further, the macaroon could be encrypted with the user's password. This way depending on the nature of the macaroon (admin, readonly, ...) the user would automatically have the correct permissions on lnd and the macaroon would not be stored as clear text in the configuration/database.

**Comment by saubyk** [comment]
> For the (not so) far future, it would be cool if multiple users could be defined, for example in a small sqlite database, with a different lnd configuration for each user. This way one instance of the RTL installation could be used for multiple lnds. Also, the macaroon could be optionally provided as a hex string and not a path (we are running multiple lnds on multiple servers and RTL would typically run on a separate server / cluster of servers as a front-end to the lnds farm). Also different permission levels (read-only, read-write ...) would be appreciated.

@ketominer Thanks for your inputs. I believe, you are referring to two different requirements in your comment. One is related to user roles and other is for controlling different LND nodes via a single RTL UI. For the latter, I  have created a separate issue, please take a look at provide any additional comments if you would like:
https://github.com/ShahanaFarooqui/RTLFullApplication/issues/4

**Comment by saubyk** [comment]
@rootzoll  @ketominer 

We have completed the basic authentication functionality on RTL.
Please review the documentation required to make it work.
https://github.com/ShahanaFarooqui/RTL/blob/master/README.md

RTL.conf is required now for the application to boot and auth to work, and it is located on the root folder of the app.
Let us know if you have additional questions.
Thanks

**Comment by rootzoll** [comment]
For the RaspiBlitz I fixed the version getting installed to v.0.1.7-alpha.
It setups the RTL.conf with nodeAuthType=DEFAULT and everything seems to look fine.

The only thing I that is a bit confusing - that the login and the wallet unlock looks kind of similar - would be great if that visually get a bit more different.

Also its a bit hard to remember that the login password was is the Password B - not Password A ... like on SSH login. Is there anyway to add some additional info/reminder text? 

For example if the "nodeAuthType=DEFAULT" the form lable "Password" could change to "RPC Password" or even display a short text unter des form like:  Use the RPC password (B) of your node to login in.

**Comment by saubyk** [comment]
@rootzoll I ve created a new issue to tackle this.

https://github.com/ShahanaFarooqui/RTLFullApplication/issues/5

Please take a look and comment if you would like.

Thanks
