### ISSUE TITLE
About creating a Certificate using OpenSSL.

### ISSUE THREAD

**Issue by educob** [ShahanaFarooqui/RTLFullApplication#3]
Hi.

I just read this article: [https://www.scipioerp.com/2018/12/12/is-lightning-ready-for-commerce/](url)

In the article they say: 
"Unlock the wallet. This will generate a TLS certificate and key. If you want to access the wallet from an external system (and you managed to configure lightning to allow the access from that specific IP), you will have to make sure that your wallet is unlocked with a specific kind of certificate (x509 P-256 curve). The certificate Lightning creates is not of the right kind, so you will have to create it yourself with OpenSSL and override the original cert. Remember to restart lnd and unlock the wallet once the cert is changed and write down the cert location for later"

What do you think about this creating a certificate using Open SSL?

thanks.

**Comment by saubyk** [comment]
We are working on this. Will provide an update on this soon. Thanks.
