### ISSUE TITLE
Control Multiple LND nodes via RTL

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTLFullApplication#4]
**Introduction**
Control multiple LND nodes via one RTL instance.

**Config Changes**
Add following sections in the RTL.conf file.
1. To specify if RTL is controlling single or multiple node instances.
[NODEINSTANCE]
Single/Multiple
For ‘Single’ instance, RTL will assume the node IP address to be the same as the server which the app is running on.
For ‘Multiple’ instance, RTL would expect the specific IP addresses+port number to be provided, for the LND nodes.
2. In case of ‘Multiple’ instance, specify the IP addresses:port number of the LND Nodes.
[NODEADDRESSES]
E.g.
192.168.0.2:9735
192.168.0.5:19735

**UI Changes**
An additional top level page will be created, which will show different nodes configured based on the IP addressed provided in RTL.conf. User will be able to click on each node separately and navigate to each node.

**Comment by ketominer** [comment]
IP:PORT would be in my opinion better as lnds may be running on one host (for example in containers). How would the authentication for each lnd be handled?

**Comment by ketominer** [comment]
I tried to illustrate one way of dealing with this + #2 
![document_2018-12-28_17-18-08](https://user-images.githubusercontent.com/43620256/50521819-d92ebf80-0ac7-11e9-93b0-ff50842bd2f6.png)
