### ISSUE TITLE
Differentiate b/w RTL login and LND Unlock

### ISSUE THREAD

**Issue by saubyk** [ShahanaFarooqui/RTLFullApplication#5]
To clearly differentiate b/w RTL login and LND unlock, following can be done:

Login page to RTL, needs to be labelled 'Login to RTL'
In case the authtype is DEFAULT, login page should also indicate 'Enter RPC password'.

Unlock page for LND, needs to be labelled 'Unlock LND'
Unlock page should also indicate, 'Enter LND Wallet Password'.

**Comment by rootzoll** [comment]
Perfect :) Will there be a tagged release after "v0.1.7-alpha" soon containing this fix? Because in RaspiBlitz I will now set install of RTL to a tagged release - 0.1.7 at the moment.

**Comment by saubyk** [comment]
@rootzoll
Yes a new release will be tagged by Saturday. We are working on adding one more feature, to allow update of channels.

**Comment by rootzoll** [comment]
Thats good timing - I plan to package next raspiBlitz release for next monday :)
