### ISSUE TITLE
RTL vs RTLFullApplication

### ISSUE THREAD

**Issue by w4cky** [ShahanaFarooqui/RTLFullApplication#6]
Hi
What is the difference between RTL and RTLFullApplication?

**Comment by saubyk** [comment]
Hi,
RTLFullApplication is complete code repository with Angular code base.
We did not want the end user to get confused with all build and compile time complexities.
So we decided to create a separate repo which contains the final build for end users to install directly.

If you want to inspect or contribute to the code base of the app, you should do that in RTLFullApplication.
Thanks.

**Comment by ShahanaFarooqui** [comment]
Closing this issue now. Please let us know if you have further queries. Thanks.
