### ISSUE TITLE
RTL unable to login Password Not Found In LND Config! V0.2.15 beta

### ISSUE THREAD

**Issue by PapaCoderNit** [ShahanaFarooqui/RTLFullApplication#7]
Im on version 1.1 Im not able to login RTL
i get the error msg Password Not Found In LND Config!

i reset my rpc (b) password.
uninstalled and reinstalled RTL
<img width="1348" alt="Screen Shot 2019-03-28 at 3 07 31 PM" src="https://user-images.githubusercontent.com/25369917/55238294-840b6280-520a-11e9-9c1a-3e80ee9086f4.png">

**Comment by saubyk** [comment]
Hi,

Can you share your lnd.conf?
Don't forget to mask your password and other sensitive info. Thanks.

**Comment by PapaCoderNit** [comment]
I typed in the real password that is found in the lnd.conf and still not working



# lnd configuration

[Application Options]
debuglevel=debug
maxpendingchannels=5
alias=Mxxxxxx
color=#68F442
nat=false

# RPC open to all connections on Port 10009
rpclisten=0.0.0.0:10009
# REST open to all connections on Port 8080
restlisten=0.0.0.0:8080

# Domain, could use https://freedns.afraid.org
#tlsextradomain=lightning.yourhost.com
tlsextraip=0.0.0.0

[Litecoin]
litecoin.active=1
litecoin.mainnet=1
litecoin.node=litecoind

[Litecoind]
litecoind.rpchost=127.0.0.1
litecoind.rpcuser=raspibolt
litecoind.rpcpass=Bxx.xxxxx.xxxxx.xxx
litecoind.zmqpubrawblock=tcp://*:28332
litecoind.zmqpubrawtx=tcp://*:28333

[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.6

**Comment by saubyk** [comment]
Hi @PapaCoderNit 
Are you entering the same password as specified in `litecoind.rpcpass`?

you can also try the custom password setting, instead of using the one in lnd.conf.
set the following in your `RTL.conf` file:
`nodeAuthType=CUSTOM`
and `rtlPass` to your custom password value.

additionally, please shift over to [RTL](https://github.com/ShahanaFarooqui/RTL) repo, as we are planning to delete this repo soon.

Thanks

**Comment by goodc0re** [comment]
Having the same issue, installed RTL via raspiblitz, I believe like PapaCoderNit. 
I tried editing the RTL.conf with CUSTOM and a custom password but it still doesn't work. 
Message
:
Authentication Failed!
Error
:
Password Not Found In LND Config!

**Comment by saubyk** [comment]
@goodc0re are your running on lnd on litecoind?
